query {
  __schema {
    mutationType {
      fields {
        name
      }
    }
    queryType {
      fields {
        name
      }
    }
    subscriptionType {
      fields {
        name
      }
    }
  }
}
